//! Differential correctness against the benchmark fixtures, when they exist.
//!
//! `bench/fixtures` is gitignored and regenerated by `cargo xtask fixtures`.
//! These tests skip themselves when a fixture is absent so a fresh checkout
//! still has a green suite; on a bench machine they are the large-input half of
//! the differential check, decoding in deliberately awkward chunk sizes and
//! comparing length and CRC32 against `xz -dc`.

mod common;

use std::process::{Command, Stdio};

use common::*;

fn crc32(buf: &[u8], seed: u32) -> u32 {
    // Bitwise IEEE CRC32; slow, but it runs once per fixture on the test's own
    // output and keeps the crate's dev-dependency list empty.
    let mut crc = !seed;
    for &b in buf {
        crc ^= u32::from(b);
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                0xEDB8_8320 ^ (crc >> 1)
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

/// Runs `xz -dc` on the fixture and returns its output length and CRC32,
/// without ever holding the whole gigabyte in memory.
fn oracle(args: &[&str]) -> Option<(u64, u32)> {
    let mut child = Command::new("xz")
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdout = child.stdout.take()?;
    let mut buf = vec![0u8; 1 << 20];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        use std::io::Read;
        let n = stdout.read(&mut buf).ok()?;
        if n == 0 {
            break;
        }
        len += n as u64;
        crc = crc32(&buf[..n], crc);
    }
    child.wait().ok()?.success().then_some((len, crc))
}

/// Streams the fixture through the decoder in `in_chunk`-sized input slices
/// and `out_chunk`-sized output slices, returning length and CRC32.
fn ours_lzma1(data: &[u8], in_chunk: usize, out_chunk: usize) -> (u64, u32) {
    use lzma_turbo::{FinishMode, LzmaAloneHeader, LzmaDecoder, Status};
    let header: [u8; 13] = data[..13].try_into().unwrap();
    let props = LzmaAloneHeader::parse(&header).unwrap().props;
    let mut dec = LzmaDecoder::new(props).unwrap();
    let mut input = &data[13..];
    let mut out = vec![0u8; out_chunk];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        let feed = in_chunk.min(input.len());
        let p = dec
            .decode(&input[..feed], &mut out, FinishMode::Any)
            .expect("fixture decodes");
        input = &input[p.read..];
        len += p.written as u64;
        crc = crc32(&out[..p.written], crc);
        if p.status == Status::FinishedWithMark || (p.read == 0 && p.written == 0) {
            break;
        }
    }
    (len, crc)
}

fn ours_lzma2(dict_prop: u8, payload: &[u8], in_chunk: usize, out_chunk: usize) -> (u64, u32) {
    use lzma_turbo::{FinishMode, Lzma2Decoder, Status};
    let mut dec = Lzma2Decoder::new(dict_prop).unwrap();
    let mut input = payload;
    let mut out = vec![0u8; out_chunk];
    let mut len = 0u64;
    let mut crc = 0u32;
    loop {
        let feed = in_chunk.min(input.len());
        let p = dec
            .decode(&input[..feed], &mut out, FinishMode::Any)
            .expect("fixture decodes");
        input = &input[p.read..];
        len += p.written as u64;
        crc = crc32(&out[..p.written], crc);
        if p.status == Status::FinishedWithMark || (p.read == 0 && p.written == 0) {
            break;
        }
    }
    (len, crc)
}

/// Odd sizes on purpose: 1 and 7 keep the decoder in the `tempBuf` path, 4096
/// straddles symbol boundaries arbitrarily, 1 MiB is the shape a real caller
/// uses.
const CHUNKS: &[(usize, usize)] = &[(1, 4096), (7, 1), (4096, 4096), (1 << 20, 1 << 20)];

#[test]
fn lzma1_fixtures_match_xz() {
    for name in ["p256.bin.lzma", "payload.bin.lzma"] {
        let path = repo_root().join("bench/fixtures").join(name);
        let Ok(data) = std::fs::read(&path) else {
            eprintln!("skipping {name}: fixture absent (run `cargo xtask fixtures`)");
            continue;
        };
        let Some(expected) = oracle(&["-dc", "-T1", "--format=lzma", path.to_str().unwrap()])
        else {
            eprintln!("skipping {name}: xz oracle unavailable");
            continue;
        };
        // The 1-byte-at-a-time lanes are quadratic in a gigabyte; run the
        // awkward chunk sizes on the smaller fixture only.
        let chunks: &[(usize, usize)] = if data.len() > (1 << 29) {
            &[(1 << 20, 1 << 20)]
        } else {
            CHUNKS
        };
        for &(in_chunk, out_chunk) in chunks {
            let got = ours_lzma1(&data, in_chunk, out_chunk);
            assert_eq!(got, expected, "{name} ({in_chunk},{out_chunk})");
        }
    }
}

#[test]
fn lzma2_fixtures_match_xz() {
    let name = "p256.bin.xz";
    let path = repo_root().join("bench/fixtures").join(name);
    let Ok(data) = std::fs::read(&path) else {
        eprintln!("skipping {name}: fixture absent (run `cargo xtask fixtures`)");
        return;
    };
    let Some(expected) = oracle(&["-dc", "-T1", path.to_str().unwrap()]) else {
        eprintln!("skipping {name}: xz oracle unavailable");
        return;
    };
    let (dict_prop, payload) = xz_lzma2_block(&data).expect("single LZMA2 block");
    for &(in_chunk, out_chunk) in CHUNKS {
        let got = ours_lzma2(dict_prop, payload, in_chunk, out_chunk);
        assert_eq!(got, expected, "{name} ({in_chunk},{out_chunk})");
    }
}

/// The `.7z` fixtures are single-file, single-folder archives, so the LZMA2
/// pack stream is one byte range and the dictionary property byte is in the
/// coder properties. Nothing here parses a real 7z; see the helper's own
/// module docs.
#[test]
fn the_seven_z_fixtures_are_one_lzma2_pack_stream() {
    for name in ["mt.7z", "st.7z"] {
        let path = repo_root().join("bench/fixtures").join(name);
        let Ok(data) = std::fs::read(&path) else {
            eprintln!("skipping {name}: fixture absent (run `cargo xtask fixtures`)");
            continue;
        };
        let ps = sevenz::pack_stream(&data)
            .unwrap_or_else(|| panic!("{name}: not a single-folder LZMA2 archive"));
        // 32 is the size of the signature header, which is where a 7z archive
        // written in one pass puts the first pack stream.
        assert_eq!(ps.offset, 32, "{name}");
        assert_eq!(ps.unpacked_len, 1 << 30, "{name}");
        assert_eq!(ps.dict_prop, 26, "{name}");
        assert!(ps.offset + ps.packed_len <= data.len() as u64, "{name}");
    }
}

/// Runs a command that writes the decoded bytes to stdout and returns the
/// length and CRC32 of what came out.
#[cfg(feature = "std")]
fn stdout_oracle(prog: &str, args: &[&str]) -> Option<(u64, u32)> {
    let mut child = Command::new(prog)
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    let mut stdout = child.stdout.take()?;
    let mut buf = vec![0u8; 1 << 20];
    let (mut len, mut crc) = (0u64, 0u32);
    loop {
        use std::io::Read;
        let n = stdout.read(&mut buf).ok()?;
        if n == 0 {
            break;
        }
        len += n as u64;
        crc = crc32(&buf[..n], crc);
    }
    child.wait().ok()?.success().then_some((len, crc))
}

/// The gigabyte fixtures through the parallel decoder, at several thread
/// counts, against both this crate's single-threaded path and 7-Zip itself.
///
/// `mt.7z` was written with `-mmt=on` and so has many independently decodable
/// runs; `st.7z` was written with `-mmt=1` and has exactly one, which is the
/// case the parallel decoder has to fall back to single-threaded without
/// buffering the stream.
#[cfg(feature = "std")]
#[test]
fn lzma2_mt_fixtures_match_the_single_threaded_path() {
    use lzma_turbo::{Lzma2MtOptions, Lzma2ParallelDecoder};

    let all = std::thread::available_parallelism().map_or(1, std::num::NonZero::get);
    for name in ["mt.7z", "st.7z"] {
        let path = repo_root().join("bench/fixtures").join(name);
        let Ok(data) = std::fs::read(&path) else {
            eprintln!("skipping {name}: fixture absent (run `cargo xtask fixtures`)");
            continue;
        };
        let ps = sevenz::pack_stream(&data).expect("single-folder LZMA2 archive");
        let payload = &data[ps.offset as usize..(ps.offset + ps.packed_len) as usize];

        let expected = ours_lzma2(ps.dict_prop, payload, 1 << 20, 1 << 20);
        assert_eq!(expected.0, ps.unpacked_len, "{name}: declared size");

        // The full 1/2/3/8/16 sweep is the small-vector differential test's
        // job; at a gigabyte a run each, three points are enough to show the
        // large-input path agrees.
        for threads in [1, 2, all] {
            let opts = Lzma2MtOptions {
                threads,
                memory_limit: u64::MAX,
            };
            let dec = Lzma2ParallelDecoder::new(ps.dict_prop, &opts).unwrap();
            let mut sink = CrcSink::default();
            let n = dec.decode(payload, &mut sink).expect("fixture decodes");
            assert_eq!((n, sink.finish()), expected, "{name} at {threads} threads");
        }

        match stdout_oracle("7zz", &["x", "-so", path.to_str().unwrap()]) {
            Some(o) => assert_eq!(o, expected, "{name}: 7zz disagrees"),
            None => eprintln!("skipping the 7zz oracle for {name}: unavailable"),
        }
    }
}

/// A [`std::io::Write`] that keeps only the length and CRC32, so a gigabyte of
/// output never has to be resident.
#[cfg(feature = "std")]
#[derive(Default)]
struct CrcSink {
    crc: u32,
    #[cfg(feature = "crc")]
    digest: Option<lzma_turbo::crc::Crc32>,
}

#[cfg(feature = "std")]
impl std::io::Write for CrcSink {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        // Deliberately the crate's own carry-less CRC when it is compiled in,
        // not the bitwise `crc32` above. On the parallel path this sink runs
        // inside the ring's one serialised write section, so a slow checksum
        // here is charged to the decoder *and* stalls every other worker - the
        // exact effect measured in docs/perf-log.md, and the reason
        // `Checksum`/`ChecksumPlan` exist. A bitwise CRC here made this file
        // take twelve minutes.
        #[cfg(feature = "crc")]
        {
            self.digest
                .get_or_insert_with(lzma_turbo::crc::Crc32::new)
                .update(buf);
        }
        #[cfg(not(feature = "crc"))]
        {
            self.crc = crc32(buf, self.crc);
        }
        Ok(buf.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

#[cfg(feature = "std")]
impl CrcSink {
    /// The CRC of everything written, consuming the sink.
    #[cfg_attr(not(feature = "crc"), allow(unused_mut))]
    fn finish(mut self) -> u32 {
        #[cfg(feature = "crc")]
        {
            self.crc = self
                .digest
                .take()
                .map_or(0, lzma_turbo::crc::Crc32::finalize);
        }
        self.crc
    }
}

// ---------------------------------------------------------------------------
// Worker-side checksums on the gigabyte fixtures
// ---------------------------------------------------------------------------

/// A sink that reproduces, serially and in order, exactly what the workers are
/// supposed to have computed in parallel: a CRC-32 and a CRC-64/XZ of every
/// piece between `splits`, and a SHA-256 of every span between `block_ends`.
///
/// This is the oracle the parallel path is checked against, and it is built
/// the slow, obvious way on purpose - one pass, one thread, no folding.
#[cfg(all(feature = "std", feature = "crc"))]
#[derive(Default)]
struct RefSink {
    splits: Vec<u64>,
    block_ends: Vec<u64>,
    pos: u64,
    split_at: usize,
    block_at: usize,
    seg_start: u64,
    c32: Option<lzma_turbo::crc::Crc32>,
    c64: Option<lzma_turbo::crc::Crc64Xz>,
    segments: Vec<(u64, u64, u32, u64)>,
    #[cfg(any(feature = "crypto", feature = "native-crypto"))]
    sha: Option<lzma_turbo::crypto::Sha256>,
    #[cfg(any(feature = "crypto", feature = "native-crypto"))]
    digests: Vec<(u64, u64, [u8; 32])>,
    sha_start: u64,
}

#[cfg(all(feature = "std", feature = "crc"))]
impl RefSink {
    fn new(splits: Vec<u64>, block_ends: Vec<u64>) -> Self {
        RefSink {
            splits,
            block_ends,
            c32: Some(lzma_turbo::crc::Crc32::new()),
            c64: Some(lzma_turbo::crc::Crc64Xz::new()),
            #[cfg(any(feature = "crypto", feature = "native-crypto"))]
            sha: Some(lzma_turbo::crypto::Sha256::new()),
            ..Default::default()
        }
    }

    /// The next absolute offset at which something must be closed off.
    /// Both lists are sorted, and `pos` only ever moves forward, so the cursors
    /// do too: this is a merge, not a search.
    fn next_cut(&self) -> Option<u64> {
        let a = self.splits.get(self.split_at).copied();
        let b = self.block_ends.get(self.block_at).copied();
        match (a, b) {
            (Some(a), Some(b)) => Some(a.min(b)),
            (x, y) => x.or(y),
        }
    }

    fn close_segment(&mut self) {
        if self.pos == self.seg_start {
            return;
        }
        let c32 = self.c32.take().expect("open").finalize();
        let c64 = self.c64.take().expect("open").finalize();
        self.segments
            .push((self.seg_start, self.pos - self.seg_start, c32, c64));
        self.c32 = Some(lzma_turbo::crc::Crc32::new());
        self.c64 = Some(lzma_turbo::crc::Crc64Xz::new());
        self.seg_start = self.pos;
    }

    #[cfg(any(feature = "crypto", feature = "native-crypto"))]
    fn close_block(&mut self) {
        if self.pos == self.sha_start {
            return;
        }
        let d = self.sha.take().expect("open").finalize();
        self.digests
            .push((self.sha_start, self.pos - self.sha_start, d));
        self.sha = Some(lzma_turbo::crypto::Sha256::new());
        self.sha_start = self.pos;
    }

    #[cfg(not(any(feature = "crypto", feature = "native-crypto")))]
    fn close_block(&mut self) {
        self.sha_start = self.pos;
    }

    fn finish(mut self) -> Self {
        self.close_segment();
        self.close_block();
        self
    }
}

#[cfg(all(feature = "std", feature = "crc"))]
impl std::io::Write for RefSink {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        let total = buf.len();
        let mut buf = buf;
        while !buf.is_empty() {
            let take = match self.next_cut() {
                Some(c) if c < self.pos + buf.len() as u64 => (c - self.pos) as usize,
                _ => buf.len(),
            };
            let (head, tail) = buf.split_at(take);
            self.c32.as_mut().expect("open").update(head);
            self.c64.as_mut().expect("open").update(head);
            #[cfg(any(feature = "crypto", feature = "native-crypto"))]
            self.sha.as_mut().expect("open").update(head);
            self.pos += take as u64;
            buf = tail;

            // Close off whatever ends exactly here. A block end is also a
            // segment end, because a worker never produces a segment that
            // spans two blocks.
            let mut cut = false;
            while self.splits.get(self.split_at) == Some(&self.pos) {
                self.split_at += 1;
                cut = true;
            }
            let mut block = false;
            while self.block_ends.get(self.block_at) == Some(&self.pos) {
                self.block_at += 1;
                block = true;
            }
            if cut || block {
                self.close_segment();
            }
            if block {
                self.close_block();
            }
        }
        Ok(total)
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

/// The parallel decoder's worker-side checksums, on a gigabyte, against a
/// serial oracle over the same bytes.
///
/// The point of the feature is that the CRCs are computed by the workers and
/// folded afterwards; the point of the test is that folding them gives exactly
/// what checksumming the whole thing serially would have, for every range a
/// consumer could ask about - including ranges that straddle the decoder's own
/// block boundaries, which is the case a 7z sub-stream hits.
#[cfg(all(feature = "std", feature = "crc"))]
#[test]
fn lzma2_mt_fixture_checksums_fold_to_the_serial_answer() {
    use lzma_turbo::crc::CrcFolder;
    use lzma_turbo::{Checksum, ChecksumPlan, Lzma2MtOptions, Lzma2ParallelDecoder};

    let all = std::thread::available_parallelism().map_or(1, std::num::NonZero::get);
    let path = repo_root().join("bench/fixtures/mt.7z");
    let Ok(data) = std::fs::read(&path) else {
        eprintln!("skipping: mt.7z absent (run `cargo xtask fixtures`)");
        return;
    };
    let ps = sevenz::pack_stream(&data).expect("single-folder LZMA2 archive");
    let payload = &data[ps.offset as usize..(ps.offset + ps.packed_len) as usize];
    let total = ps.unpacked_len;

    let opts = |threads: usize| Lzma2MtOptions {
        threads,
        memory_limit: u64::MAX,
    };
    let decode = |threads: usize, plan: &ChecksumPlan| {
        let dec = Lzma2ParallelDecoder::new(ps.dict_prop, &opts(threads)).unwrap();
        // A counting sink, not a checksumming one: the oracle for these bytes
        // is `RefSink` on its own pass, and anything done in this sink would be
        // done inside the ring's serialised section.
        let sink = std::io::sink();
        let (n, checks) = dec
            .decode_checksummed(payload, sink, plan)
            .expect("fixture decodes");
        assert_eq!(n, total, "{threads} threads: short decode");
        checks
    };

    // Awkward on purpose: 1 is inside the first run, the 12.5 MiB stride lands
    // all over the inside of every run, and 128 MiB is exactly a run boundary
    // in this fixture - the place an off-by-one between a block's start and a
    // segment's start would hide.
    let mut splits = vec![1u64, 3];
    let mut p = 13_107_200u64;
    while p < total {
        splits.push(p);
        p += 13_107_200;
    }
    let run = 128u64 << 20;
    let mut b = run;
    while b < total {
        splits.push(b - 1);
        splits.push(b);
        splits.push(b + 1);
        b += run;
    }
    splits.sort_unstable();
    splits.dedup();

    // What the workers produced, at four thread counts. Block boundaries are
    // taken from the widest run, which is the one with the most of them.
    let mut per_threads = Vec::new();
    for t in [1, 2, 8, all.max(16)] {
        per_threads.push((
            t,
            decode(
                t,
                &ChecksumPlan::new(Checksum::Crc32).with_split_points(splits.clone()),
            ),
            decode(
                t,
                &ChecksumPlan::new(Checksum::Crc64Xz).with_split_points(splits.clone()),
            ),
        ));
    }
    // Whole-block checks, from a run with no split points. SHA-256 where the
    // crate has it, because the digest comparison at the end needs this same
    // run; a plain CRC otherwise - the block boundaries are the decoder's and
    // do not depend on which check is asked for.
    #[cfg(any(feature = "crypto", feature = "native-crypto"))]
    let sha_blocks = decode(all.max(16), &ChecksumPlan::new(Checksum::Sha256));
    #[cfg(not(any(feature = "crypto", feature = "native-crypto")))]
    let sha_blocks = decode(all.max(16), &ChecksumPlan::new(Checksum::Crc32));
    let block_ends: Vec<u64> = sha_blocks
        .iter()
        .map(|c| c.unpacked_offset + c.len)
        .collect();
    assert!(
        block_ends.len() > 1,
        "mt.7z should decode as several blocks, got {}",
        block_ends.len()
    );

    // One serial pass over the same bytes for the oracle.
    let reference = {
        let dec = Lzma2ParallelDecoder::new(ps.dict_prop, &opts(1)).unwrap();
        let mut sink = RefSink::new(splits.clone(), block_ends.clone());
        dec.decode(payload, &mut sink).expect("serial decode");
        sink.finish()
    };
    assert_eq!(reference.pos, total, "oracle saw the whole stream");

    // Every range the split points bound must fold to the serial answer, at
    // every thread count, at both widths.
    let mut edges = splits.clone();
    edges.insert(0, 0);
    edges.push(total);
    for (t, c32, c64) in &per_threads {
        let mut f32 = CrcFolder::<u32>::new();
        for s in c32.iter().flat_map(|c| c.segments.iter()) {
            f32.push(s.offset, s.len, s.check.crc32().expect("crc32"));
        }
        let mut f64 = CrcFolder::<u64>::new();
        for s in c64.iter().flat_map(|c| c.segments.iter()) {
            f64.push(s.offset, s.len, s.check.crc64().expect("crc64"));
        }

        // Piece by piece against the oracle's own pieces...
        let mut pos = 0u64;
        for &(off, len, want32, want64) in &reference.segments {
            assert_eq!(off, pos, "oracle segments do not tile");
            assert_eq!(
                f32.range(off, len),
                Some(want32),
                "{t} threads: crc32 {off}"
            );
            assert_eq!(
                f64.range(off, len),
                Some(want64),
                "{t} threads: crc64 {off}"
            );
            pos += len;
        }
        assert_eq!(pos, total);

        // ...and over ranges that straddle several of them, including the
        // decoder's block boundaries.
        for w in edges.windows(5) {
            let (a, b) = (w[0], w[4]);
            assert!(f32.range(a, b - a).is_some(), "{t} threads: gap {a}..{b}");
            assert!(f64.range(a, b - a).is_some(), "{t} threads: gap {a}..{b}");
        }
        assert!(
            f32.range(0, total).is_some() && f64.range(0, total).is_some(),
            "{t} threads: the whole output must fold"
        );
    }

    // SHA-256 is per block and must match a serial digest of the same span.
    #[cfg(any(feature = "crypto", feature = "native-crypto"))]
    {
        assert_eq!(sha_blocks.len(), reference.digests.len());
        for (c, &(off, len, want)) in sha_blocks.iter().zip(reference.digests.iter()) {
            assert_eq!((c.unpacked_offset, c.len), (off, len), "block spans");
            assert!(c.segments.is_empty(), "sha256 must not segment");
            assert_eq!(c.digest, Some(want), "digest of the block at {off}");
        }
    }
}
